name: mpv clang
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  build_mpv:
    name: Building mpv (64-bit)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bit: [x86_64]
    env:
      BIT: ${{ matrix.bit }}
    container:
      image: docker://ghcr.io/shinchiro/archlinux:latest

    steps:
      - name: Init variable
        run: |
          echo "arch=x86_64" >> $GITHUB_ENV

      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main
        with:
          ref: master

      - name: Loading clang sysroot cache
        uses: actions/cache/restore@main
        with:
          path: clang_root
          key: clang_root-${{ github.run_id }}
          restore-keys: clang_root

      - name: Loading repository cache
        uses: actions/cache/restore@main
        with:
          path: src_packages
          key: repository-${{ github.run_id }}
          restore-keys: repository

      - name: Loading toolchain cache
        uses: actions/cache/restore@main
        with:
          path: build_${{ matrix.bit }}
          key: clang-${{ matrix.bit }}_toolchain-${{ github.run_id }}
          restore-keys: clang-${{ matrix.bit }}_toolchain

      - name: Configuring CMake & Downloading source
        run: |
          cmake -DTARGET_ARCH=${{ env.arch }}-w64-mingw32 -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_$BIT/$BIT-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -DRUSTUP_LOCATION=$PWD/clang_root/install_rustup -DENABLE_CCACHE=ON -DCLANG_PACKAGES_LTO=ON -G Ninja --fresh -B build_$BIT -S $PWD
          ninja -C build_$BIT download || true

      - name: Building mpv
        run: |
          ninja -C build_$BIT update
          ninja -C build_$BIT mpv

      - name: Packaging mpv
        run: |
          mkdir -p release_$BIT
          ninja -C build_$BIT mpv-packaging
          mv build_$BIT/mpv*.7z release_$BIT/

      - name: Uploading mpv build artifact
        uses: actions/upload-artifact@main
        with:
          name: mpv-custom-x86_64
          path: release_${{ matrix.bit }}/mpv*.7z
          retention-days: 7
